apiVersion: v1
kind: Service
metadata:
  name: my-app-loadbalancer-service
spec:
  type: LoadBalancer #Defaults to ClusterIP. Options are ExternalName, ClusterIP, NodePort, and LoadBalancer
  selector: #Route service traffic to pods with label keys and values matching this selector (backend opts)
    app: myapp
  ports: #list of ports exposed by this service
    - name: http
      port: 80 #Service port
      targetPort: 80 #Container port